// Code generated by protoc-gen-go.
// source: github.com/micro/profile-srv/proto/record/record.proto
// DO NOT EDIT!

/*
Package record is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/profile-srv/proto/record/record.proto

It has these top-level messages:
	Profile
	CreateRequest
	CreateResponse
	DeleteRequest
	DeleteResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	SearchRequest
	SearchResponse
*/
package record

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Profile struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Owner       string `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
	Type        int64  `protobuf:"varint,4,opt,name=type" json:"type,omitempty"`
	DisplayName string `protobuf:"bytes,6,opt,name=displayName" json:"displayName,omitempty"`
	Blurb       string `protobuf:"bytes,7,opt,name=blurb" json:"blurb,omitempty"`
	Url         string `protobuf:"bytes,8,opt,name=url" json:"url,omitempty"`
	Location    string `protobuf:"bytes,9,opt,name=location" json:"location,omitempty"`
	Created     int64  `protobuf:"varint,10,opt,name=created" json:"created,omitempty"`
	Updated     int64  `protobuf:"varint,11,opt,name=updated" json:"updated,omitempty"`
}

func (m *Profile) Reset()                    { *m = Profile{} }
func (m *Profile) String() string            { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()               {}
func (*Profile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateRequest struct {
	Profile *Profile `protobuf:"bytes,1,opt,name=profile" json:"profile,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ReadResponse struct {
	Profile *Profile `protobuf:"bytes,1,opt,name=profile" json:"profile,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReadResponse) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type UpdateRequest struct {
	Profile *Profile `protobuf:"bytes,1,opt,name=profile" json:"profile,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateRequest) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type SearchRequest struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Owner  string `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
	Limit  int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SearchResponse struct {
	Profiles []*Profile `protobuf:"bytes,1,rep,name=profiles" json:"profiles,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchResponse) GetProfiles() []*Profile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func init() {
	proto.RegisterType((*Profile)(nil), "Profile")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Record service

type RecordClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type recordClient struct {
	c           client.Client
	serviceName string
}

func NewRecordClient(serviceName string, c client.Client) RecordClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "record"
	}
	return &recordClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *recordClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Record.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Record.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Record.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Record.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Record.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Record service

type RecordHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterRecordHandler(s server.Server, hdlr RecordHandler) {
	s.Handle(s.NewHandler(&Record{hdlr}))
}

type Record struct {
	RecordHandler
}

func (h *Record) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.RecordHandler.Create(ctx, in, out)
}

func (h *Record) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.RecordHandler.Read(ctx, in, out)
}

func (h *Record) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.RecordHandler.Delete(ctx, in, out)
}

func (h *Record) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.RecordHandler.Update(ctx, in, out)
}

func (h *Record) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.RecordHandler.Search(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x93, 0xdd, 0x6a, 0xe3, 0x30,
	0x10, 0x85, 0xe3, 0x38, 0x6b, 0x3b, 0xe3, 0xd8, 0x09, 0xda, 0x1b, 0x25, 0x7b, 0xb3, 0x18, 0x16,
	0xf6, 0xd7, 0x81, 0x2c, 0xec, 0x0b, 0xec, 0xde, 0x2d, 0x94, 0x92, 0xd2, 0x07, 0xf0, 0x8f, 0xd2,
	0x08, 0x6c, 0xcb, 0x95, 0xe5, 0x96, 0x3c, 0x50, 0x9f, 0xac, 0x2f, 0x52, 0x59, 0xb2, 0x5a, 0x3b,
	0x94, 0xd2, 0xab, 0x64, 0x46, 0xdf, 0x0c, 0x67, 0xce, 0x49, 0xe0, 0xcf, 0x0d, 0x15, 0xc7, 0x36,
	0x8d, 0x33, 0x56, 0x6e, 0x4b, 0x9a, 0x71, 0xb6, 0xad, 0x39, 0x3b, 0xd0, 0x82, 0xfc, 0x6a, 0xf8,
	0x5d, 0xf7, 0x5d, 0xb0, 0x2d, 0x27, 0x19, 0xe3, 0x79, 0xff, 0x11, 0xab, 0x5e, 0xf4, 0x60, 0x81,
	0x7b, 0xa9, 0x49, 0x04, 0x30, 0xa5, 0x39, 0xb6, 0x3e, 0x5b, 0x5f, 0xe7, 0x68, 0x01, 0xb3, 0x2a,
	0x29, 0x09, 0x9e, 0xaa, 0x2a, 0x80, 0x0f, 0xec, 0xbe, 0x22, 0x1c, 0xdb, 0xe6, 0x51, 0x9c, 0x6a,
	0x82, 0x67, 0xb2, 0xb2, 0xd1, 0x47, 0xf0, 0x73, 0xda, 0xd4, 0x45, 0x72, 0xba, 0xe8, 0x26, 0x1c,
	0x33, 0x91, 0x16, 0x2d, 0x4f, 0xb1, 0xab, 0x4a, 0x1f, 0xec, 0x96, 0x17, 0xd8, 0x53, 0xc5, 0x0a,
	0xbc, 0x82, 0x65, 0x89, 0xa0, 0xac, 0xc2, 0x73, 0xd5, 0x59, 0x82, 0x9b, 0x71, 0x92, 0x08, 0x92,
	0x63, 0x50, 0x3b, 0x65, 0xa3, 0xad, 0x73, 0xd5, 0xf0, 0xbb, 0x46, 0xf4, 0x1d, 0x82, 0xbf, 0x8a,
	0xd8, 0x93, 0xdb, 0x96, 0x34, 0x02, 0xad, 0xc1, 0xed, 0x2f, 0x54, 0x8a, 0xfd, 0x9d, 0x17, 0xf7,
	0x77, 0x44, 0x2b, 0x08, 0x0d, 0xdb, 0xd4, 0xac, 0x6a, 0x48, 0xf4, 0x09, 0x82, 0x7f, 0xa4, 0x20,
	0x2f, 0xd3, 0x83, 0x53, 0x3b, 0xdc, 0x3c, 0xf6, 0xf8, 0x1a, 0xfc, 0x3d, 0x49, 0xf2, 0xd7, 0xe0,
	0x6f, 0xb0, 0xd0, 0x4f, 0x1a, 0x7d, 0x4b, 0x86, 0x94, 0x7c, 0xad, 0x6e, 0x78, 0x9f, 0x64, 0xc3,
	0xf6, 0x1a, 0xfe, 0x43, 0x70, 0x45, 0x12, 0x9e, 0x1d, 0xcd, 0xb4, 0x49, 0xc4, 0x1a, 0x27, 0xf2,
	0x1c, 0x50, 0x41, 0x4b, 0x2a, 0x54, 0x40, 0x36, 0x0a, 0xc1, 0x61, 0x87, 0x43, 0x43, 0x84, 0x8e,
	0x28, 0xfa, 0x09, 0xa1, 0x59, 0xd6, 0xeb, 0xde, 0x80, 0xd7, 0x6b, 0x69, 0xe4, 0x46, 0x7b, 0x28,
	0x66, 0xf7, 0x68, 0x81, 0xb3, 0x57, 0x3f, 0x12, 0xf4, 0x03, 0x1c, 0x6d, 0x25, 0x0a, 0xe3, 0x91,
	0xff, 0x9b, 0x65, 0x7c, 0xe6, 0xf1, 0x04, 0x7d, 0x81, 0x59, 0xe7, 0x0d, 0x5a, 0xc4, 0x03, 0xf7,
	0x36, 0x41, 0x3c, 0x34, 0x4c, 0x62, 0x72, 0xa7, 0xf6, 0x5b, 0xee, 0x1c, 0xa5, 0x22, 0x77, 0x9e,
	0x05, 0xa1, 0x60, 0x6d, 0x8c, 0x84, 0x47, 0x6e, 0x4a, 0xf8, 0xcc, 0x31, 0x05, 0xeb, 0x33, 0x25,
	0x3c, 0x32, 0x4f, 0xc2, 0xe3, 0xfb, 0xa3, 0x49, 0xea, 0xa8, 0x3f, 0xc0, 0xef, 0xa7, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x90, 0xcd, 0x28, 0xfd, 0x3a, 0x03, 0x00, 0x00,
}
